spring:
  application:
    name: auth

#  zipkin:
#    base-url: http://localhost:9411

  redis:
    host: 127.0.0.1
    database: 0

#服务端口
server:
  port: 8090

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


logging.level.org.springframework.security: DEBUG