spring:
  application:
    name: service-2

  zipkin:
    base-url: http://localhost:9411

#服务端口
server:
  port: 10212

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    #这个必须是true fetchRegistry打开才能从eureka拉取服务列表
    fetch-registry: true
  instance:
    prefer-ip-address: true

