spring:
  application:
    name: service-1

  zipkin:
    base-url: http://localhost:9411

#服务端口
server:
  port: 10211

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    #这个必须是true fetchRegistry打开才能从eureka拉取服务列表
    fetch-registry: true
  instance:
    prefer-ip-address: true

security:
  oauth2:
    resource:
      #获取当前Token的用户信息
      user-info-uri: http://localhost:8090/users/current
    client:
      id: client_2
      client-secret: 123456
      #获取Token
      access-token-uri: http://localhost:8090/oauth/token
      grant-type: client_credentials,password
      scope: server
