spring:
  application:
    name: turbine
server:
  port: 11001

turbine:
  app-config: feign
  cluster-name-expression: new String("default")
  combine-host-port: true


# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
