spring:
  application:
    name: zuul-gateway
server:
  port: 8080
#用来区分不同服务的一个名字，可以随便取
#zuul网关访问服务的一个路径
# 面向服务的路由
zuul:
  routes:
    #服务分发的方式是这样的，我们通过localhost:8080/server访问，实际是将地址映射到了server-1这个服务的地址上
    #    api-a.path: /server/**
    #所要访问的服务对应的注册中心的名称
    #    api-a.serviceId: server-1
    #另一种写法
    service-1: /service1/**
    service-2: /service2/**
    feign: /feign/**
    # 传统的路由
    #由传统的路由模式，我们可以知道用户访问的路由路径为localhost:10215/caller，将服务映射到了http://localhost:10213
#    api-b-url.path: /server/**
#    url=http: //localhost:10213/
# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10211/eureka/
    #网关不用注册到注册中心中，因为没其他微服务调用他
    register-with-eureka: false
    #这个必须是true fetchRegistry打开才能从eureka拉取服务列表
    fetch-registry: true
  instance:
    prefer-ip-address: true
