#注册中心的名字
spring:
  application:
    name: gt-eureka

  #服务端口
server:
  port: 10211
#注册中心相关配置
# 配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔（5000ms）。
eureka:
  #eureka服务端的实例名称(这里使用了虚拟主机映射，修改hosts文件即可实现)
  #  instance:
  #    hostname: eureka7001.com
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  # 不将自己注册到注册中心
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    # 注册中心的地址
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:10211/eureka/
  instance:
    prefer-ip-address: true
